apiVersion: v1
kind: Pod
metadata:
  name: base
spec:
  containers:
    - name: base
      image: your-default-image:latest
      resources:
        requests:
          memory: "1500Mi"
          cpu: "1"
        limits:
          memory: "2Gi"
          cpu: "1"